/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;


import DAO.DAO;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Model.Usuario;
import Utils.ValidEmailAddress;
import Utils.ValidaSenha;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.text.MaskFormatter;
import java.sql.Date;
import java.text.SimpleDateFormat;


/**
 *
 * @author thaina.matos
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro1
     */
    public TelaCadastro() {
        initComponents();
         this.setLocationRelativeTo(null);
        formatCampo();
    }
    
    
    private void formatCampo(){
        try {
            MaskFormatter mask = new MaskFormatter("##-##-####");
            mask.install(Teste);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro durante a formatação.", 
                                    "ERRO", JOptionPane.ERROR_MESSAGE);   
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        nomeLabel = new javax.swing.JLabel();
        TituloCadastro = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        dtnascimentoLabel = new javax.swing.JLabel();
        labelInformaSenha = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        radioFem = new javax.swing.JRadioButton();
        cadastroButton = new javax.swing.JButton();
        radioMasc = new javax.swing.JRadioButton();
        Teste = new javax.swing.JFormattedTextField();
        inputPassword = new javax.swing.JPasswordField();
        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(153, 153, 153));
        nomeLabel.setText("NOME COMPLETO");
        nomeLabel.setName("nome user"); // NOI18N
        getContentPane().add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        TituloCadastro.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        TituloCadastro.setForeground(new java.awt.Color(51, 51, 51));
        TituloCadastro.setText("Cadastrar-se");
        getContentPane().add(TituloCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        inputNome.setBackground(new java.awt.Color(224, 224, 224));
        inputNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputNome.setName("inputNome"); // NOI18N
        inputNome.setOpaque(true);
        getContentPane().add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 450, 30));

        emailLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(153, 153, 153));
        emailLabel.setText("EMAIL");
        emailLabel.setName("emailLabel"); // NOI18N
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        inputEmail.setBackground(new java.awt.Color(224, 224, 224));
        inputEmail.setName("inputEmail"); // NOI18N
        getContentPane().add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 450, 30));

        senhaLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(153, 153, 153));
        senhaLabel.setText("SENHA");
        senhaLabel.setName("senhaLabel"); // NOI18N
        getContentPane().add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        dtnascimentoLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        dtnascimentoLabel.setForeground(new java.awt.Color(153, 153, 153));
        dtnascimentoLabel.setText("DATA DE NASCIMENTO");
        dtnascimentoLabel.setName("data nascimento"); // NOI18N
        getContentPane().add(dtnascimentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        labelInformaSenha.setBackground(new java.awt.Color(204, 204, 204));
        labelInformaSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelInformaSenha.setForeground(new java.awt.Color(153, 153, 153));
        labelInformaSenha.setText(" Sua senhe deve conter 8 caracteres, letras minusculas e maiusculas.");
        getContentPane().add(labelInformaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        sexoLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(153, 153, 153));
        sexoLabel.setText("SEXO");
        getContentPane().add(sexoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        buttonGroup2.add(radioFem);
        radioFem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioFem.setForeground(new java.awt.Color(153, 153, 153));
        radioFem.setText("Feminino");
        radioFem.setContentAreaFilled(false);
        radioFem.setName("fem"); // NOI18N
        radioFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemActionPerformed(evt);
            }
        });
        getContentPane().add(radioFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, 30));

        cadastroButton.setBackground(new java.awt.Color(0, 0, 0));
        cadastroButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cadastroButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastroButton.setText("Cadastrar");
        cadastroButton.setBorder(null);
        cadastroButton.setContentAreaFilled(false);
        cadastroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroButton.setName("cadastroButton"); // NOI18N
        cadastroButton.setOpaque(true);
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 290, 50));

        buttonGroup2.add(radioMasc);
        radioMasc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        radioMasc.setForeground(new java.awt.Color(153, 153, 153));
        radioMasc.setText("Masculino");
        radioMasc.setName("masc"); // NOI18N
        radioMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMascActionPerformed(evt);
            }
        });
        getContentPane().add(radioMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 30));

        Teste.setBackground(new java.awt.Color(224, 224, 224));
        Teste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-y"))));
        Teste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteActionPerformed(evt);
            }
        });
        getContentPane().add(Teste, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 130, 30));

        inputPassword.setBackground(new java.awt.Color(224, 224, 224));
        inputPassword.setName("inputPassword"); // NOI18N
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 450, 30));

        voltarButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(51, 51, 51));
        voltarButton.setText("VOLTAR");
        voltarButton.setContentAreaFilled(false);
        voltarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarButton.setName("voltarButton"); // NOI18N
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CADASTRO PRO PROJETO (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void radioMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMascActionPerformed

    private void radioFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFemActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed

        String nome = inputNome.getText();
        String email = inputEmail.getText();
        String senha =  new String (inputPassword.getPassword());
        String dtNascimento = Teste.getText();
        String sexo = null;
        if(radioMasc.isSelected()){
            sexo = "M";
        } else {
            sexo = "F";
        }

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy"); 
        LocalDate dtNascimentoFormat = LocalDate.parse(dtNascimento, formato); 
        Date date = Date.valueOf(dtNascimentoFormat);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String dataNascimento = format.format(date);

        System.out.println(dataNascimento);
        
        Usuario usuario = new Usuario(nome, email, senha, dataNascimento, sexo);
        Usuario usuarioValida = new Usuario(email);
        DAO dao = new DAO();

        //--Valida o campo email
        ValidEmailAddress ValidEmail = new ValidEmailAddress();
        if (!((ValidEmail.isValidEmailAddress(email)))) {
            JOptionPane.showMessageDialog(null, "Por favor, digite um email válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{   //Se estiver certo continua o bloco

            if(inputNome.getText().isEmpty() == true){  //--Verifica se os input's são vazios.
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
            } else if(inputEmail.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
            } else if(inputPassword.getText().isEmpty() == true){
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
            } else if(Teste.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Preencha o campo data!");
            }
            else if (!radioMasc.isSelected() && !radioFem.isSelected()){
                JOptionPane.showMessageDialog(null, "Preencha os campos vazios!");
            }
            else { // Nenhum input vazio roda o bloco

                ValidaSenha validPassword = new ValidaSenha(); // Valida informações da senha
                if (!(validPassword.PASSWORD_PATTERN.matcher(senha).matches())) {
                    JOptionPane.showMessageDialog(null, "senha invalida, siga o formato descrito.");
                }
                else {

                    try {
                        //-- VALIDA USUARIO JÁ EXISTE
                        if (!(dao.existeEmail(usuarioValida))) {

                            dao.cadastrar(usuario);
                            JOptionPane.showMessageDialog (null, "Usuario cadastrado");
                            TelaInicialLogin telaLogin = new TelaInicialLogin(); 
                            telaLogin.setVisible(true);
                            this.dispose();

                        } else {
                            JOptionPane.showMessageDialog(null, "Email já está sendo utilizado, tente outro ou faça login", "Email já utilziado",
                                JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog (null, "ups, tente mais tarde");
                        System.out.println(e);
                    }
                    catch (Exception ex) {
                        Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    }//GEN-LAST:event_cadastroButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaInicialLogin telaLogin = new TelaInicialLogin(); 
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void TesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Teste;
    private javax.swing.JLabel TituloCadastro;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JLabel dtnascimentoLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelInformaSenha;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JRadioButton radioFem;
    private javax.swing.JRadioButton radioMasc;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
