/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.DAO;
import DAO.DAO2;
import Model.UsuarioRead;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaina.matos
 */
public class TelaControle extends javax.swing.JFrame {

    /**
     * Creates new form TelaControle
     */
    public TelaControle() {
        initComponents();
        ReadTable();
    }

    private void ReadTable() {
        DefaultTableModel model = (DefaultTableModel) RegisterTable.getModel();
        model.setNumRows(0);
        DAO2 dao2 = new DAO2();

        for (UsuarioRead p : dao2.read()) {
            model.addRow(new Object[]{
                p.getIdPessoa(),
                p.getNome(),
                p.getDataNascimento(),
                p.getEmail(),
                p.getSenha()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControleLabel = new javax.swing.JLabel();
        RemoverButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegisterTable = new javax.swing.JTable();
        fundoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ControleLabel.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        ControleLabel.setText("Tela de Controle ");
        getContentPane().add(ControleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 50));

        RemoverButton.setBackground(new java.awt.Color(0, 0, 0));
        RemoverButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        RemoverButton.setForeground(new java.awt.Color(255, 255, 255));
        RemoverButton.setText("Remover");
        RemoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RemoverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 110, 30));

        menuButton.setBackground(new java.awt.Color(153, 0, 0));
        menuButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 80, 30));

        RegisterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdPessoa", "Nome", "Data de Nascimento", "Email", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RegisterTable);
        if (RegisterTable.getColumnModel().getColumnCount() > 0) {
            RegisterTable.getColumnModel().getColumn(0).setResizable(false);
            RegisterTable.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 810, 380));

        fundoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TelaRegistro.jpg"))); // NOI18N
        getContentPane().add(fundoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RemoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverButtonActionPerformed
        if(RegisterTable.getSelectedRow() != -1){

            UsuarioRead usuario = new UsuarioRead();
            DAO dao = new DAO();
            
            usuario.setIdPessoa((int)RegisterTable.getValueAt(RegisterTable.getSelectedRow(), 0));
            dao.removerPessoa(usuario);
            
            ReadTable();
            
        }
    }//GEN-LAST:event_RemoverButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        TelaMenuAdmin telaMenu = new TelaMenuAdmin(); 
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ControleLabel;
    private javax.swing.JTable RegisterTable;
    private javax.swing.JButton RemoverButton;
    private javax.swing.JLabel fundoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuButton;
    // End of variables declaration//GEN-END:variables
}
