/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thaina.matos
 */
public class TelaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistro
     */
    public TelaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alturaLabel = new javax.swing.JLabel();
        alturaTextField = new javax.swing.JTextField();
        pesoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kgLabel = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adicionarButton1 = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        dadosTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        registroTextField = new javax.swing.JTextField();
        Register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alturaLabel.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        alturaLabel.setText("ALTURA ");
        getContentPane().add(alturaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, 30));

        alturaTextField.setBackground(new java.awt.Color(222, 221, 221));
        alturaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(alturaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 110, -1));

        pesoTextField.setBackground(new java.awt.Color(222, 221, 221));
        getContentPane().add(pesoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, -1));

        jLabel2.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        jLabel2.setText("PESO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 20));

        kgLabel.setFont(new java.awt.Font("Heiti TC", 0, 14)); // NOI18N
        kgLabel.setText("/ kg");
        getContentPane().add(kgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 20));

        editarButton.setBackground(new java.awt.Color(0, 0, 0));
        editarButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        editarButton.setForeground(new java.awt.Color(255, 255, 255));
        editarButton.setText("Editar");
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 120, 30));

        jLabel1.setFont(new java.awt.Font("Heiti TC", 0, 13)); // NOI18N
        jLabel1.setText("/ cm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 30));

        adicionarButton1.setBackground(new java.awt.Color(0, 0, 0));
        adicionarButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        adicionarButton1.setForeground(new java.awt.Color(255, 255, 255));
        adicionarButton1.setText("Registrar");
        adicionarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 120, 30));

        menuButton.setBackground(new java.awt.Color(0, 0, 0));
        menuButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 120, 30));

        removerButton.setBackground(new java.awt.Color(0, 0, 0));
        removerButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        removerButton.setForeground(new java.awt.Color(255, 255, 255));
        removerButton.setText("Remover");
        getContentPane().add(removerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 120, 30));

        dadosTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar informações corporais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        dadosTextField2.setEnabled(false);
        getContentPane().add(dadosTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 800, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data/Horário", "Altura", "Peso", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 750, 260));

        registroTextField.setForeground(new java.awt.Color(153, 153, 153));
        registroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Heiti TC", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N
        registroTextField.setCaretColor(new java.awt.Color(153, 153, 153));
        registroTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        registroTextField.setEnabled(false);
        registroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(registroTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 800, 310));

        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TelaRegistro.jpg"))); // NOI18N
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alturaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaTextFieldActionPerformed

    private void adicionarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarButton1ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

    private void registroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Register;
    private javax.swing.JButton adicionarButton1;
    private javax.swing.JLabel alturaLabel;
    private javax.swing.JTextField alturaTextField;
    private javax.swing.JTextField dadosTextField2;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JButton menuButton;
    private javax.swing.JTextField pesoTextField;
    private javax.swing.JTextField registroTextField;
    private javax.swing.JButton removerButton;
    // End of variables declaration//GEN-END:variables
}
